import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroSection from "@/components/sections/HeroSection";
import FeaturesSection from "@/components/sections/FeatureSection";
import FAQSection from "@/components/sections/FAQSection";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "converter.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body className="">
      <Navbar/>
        <main className="mx-auto w-full max-w-5xl flex-1 px-6">
          <HeroSection/>
          {/* {children} */}
          <FeaturesSection/>
          <FAQSection/>
        </main>
      <Footer/>
    </body>
    </html>
  );
}